language: node_js
node_js:
- node
services:
- postgresql
script:
- npm test
before_script:
- psql -c 'CREATE DATABASE palettepicker_test;' -U postgres
- knex migrate:latest --env=test
deploy:
  provider: heroku
  api_key:
    secure: pu5nXe7HzT6o1G4vZLc+KaeTx3XJPv9xg/zdIgzUNFsAizcA4QlrZNVvZslRF46WFbzmirEcZJRNUGCTTKuWXnUusfWbDfKdam67RWOmDGFEZgxWWxcLO5fjPn0zfNtm+Dbi5ZpkaZrRR9PLhjPgk8a7+suI2H0zxGXuXPZIcPYPpTuhBJBS0Xf83RrY4UNXiNSOCTMjRxVzD0HGFZdh8GK7GU6vMx6wpv80C8ShUlumNDaYNKdrfBRU/p0yh/vKiLPcNhAWssdSrwebycJ9ExtnwRAYI/xvGlp7c3z9vT7l3m7DcXb5ggC680OXYYiKgvjKakbAy+xvx49j0uGXdZDO4ligIbbYlMKBoYShnw+nwlqyY1one/XfJcnxyWdq549IgRydqqBn+BzZ5svnJkKWRIaUjYyv/G57U3OOoP5g9E5fcRcBVKAEN3d+SSSJ0ltHRMJ7nQczcnrJL1YoI5U99nMaEkZh9uVUIyFsHSxGBPVwqeqX77HmTSinp+0riqK4PoMqkpEM9IuEuhGiM0unxRDeQEZZ9Uv0wLv/9TMMQSrej+npMHSPwGB3ZYrewvZVeo62fAdSMjxAo6cc7HjMAZDzyQKiJQhUjVD0ZI5yJn3dmK/H59/GpddOGpSRYpKgA0+vI/XUxSy/CoLp9ri3GqGhUpdY0TMK2jZJ2JI=
  app: palette-pick-be
  skip_cleanup: true
